### ISSUE TITLE
How can windows install "torchsearchsorted"

### ISSUE THREAD

**Issue by issac-cyber** [krrish94/nerf-pytorch#7]
Any idea how can windows install torchsearchsorted? I have no idea. What operating system do u guys running (Sorry i am day 1 to programming)

**Comment by krrish94** [comment]
The various options available for setup (eg. https://github.com/krrish94/nerf-pytorch#option-1-using-pip  and https://github.com/krrish94/nerf-pytorch#option-2-using-conda) should automatically install all dependencies (including `torchsearchsorted`).

Admittedly, I haven't tested on Windows, but let me know if there's further issues.

**Comment by krrish94** [comment]
As an aside, you might be using an older version of this repo? The newer version should install all deps automatically.

**Comment by kwea123** [comment]
Colab is your good friend.

**Comment by issac-cyber** [comment]
Thanks everyone, i have tried so many way to install it in Win10 but no luck, no i am running this code on ubuntu 18.04 now, works very well (I gave up)

**Comment by pnivek** [comment]
I had issues as well. But I was able to get it working after installing missing dependencies. For me I needed the C++ 14 build tools (make sure to tick the c++ stuff in the installer). If you want to use your GPU you also need to make sure you have the right version of cuda tool kit installed when running the setup.py (for torchsearchsorted). Otherwise it will just use your CPU.
